name = "CoinGeckoAPI"
uuid = "76125105-59d2-4a1b-9579-12a806420a34"
authors = ["Gil Junqueira"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
